### ISSUE TITLE
Wrong #ifdef in pam_transient_token.c?

### ISSUE THREAD

**Issue by rrzefox** [ben-cohen/transient_token#2]
I might be holding this wrong, but I had problems getting this to work properly under Ubuntu 22.04.
It turned out that it was assuming `pam_get_authtok` to not be available, but of course it is. You're checking for `__LINUX_PAM__X` to be defined, but that macro is not defined anywhere - a grep for that comes up empty, as does a google search. Was this perhaps meant to check for `__LINUX_PAM__` without the X instead? Because changing `#elif defined(__LINUX_PAM__X)` to `#elif defined(__LINUX_PAM__)` makes it work as intended.

**Comment by ben-cohen** [comment]
Hi,
Thank you for telling me about this.  I don't remember how that happened I but I agree with what you wrote.

(In addition: I sometimes add X to the end of identifiers to "break" them, so I guess I did that for testing and forgot to remove it before committing.)

I fixed it in commit 39f1461.
